apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rnacargavalidadorms
  namespace: carga
spec:
  tags:
    - name: latest
      annotations:
        description: "Tag apuntando a la última versión de la imagen"
      from:
        kind: DockerImage
        name: azspkprdcre1000.azurecr.io/rna-carga-validador-ms:1.0.105
      importPolicy:
        scheduled: true