apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: apply-manifests-pipeline
spec:
  params:
    - name: repository
      description: URL del repositorio Git con los manifiestos
    - name: revision
      description: Rama o tag del repositorio
      default: main
    - name: apikey
      description: IBM Cloud API Key para autenticación
    - name: cluster
      description: Nombre o ID del cluster Satellite
    - name: clusterRegion
      description: Región del cluster Satellite
      default: us-south
    - name: manifestPath
      description: Ruta en el repo donde están los manifiestos (por namespace)
      default: .
  workspaces:
    - name: pipeline-pvc
  tasks:
    - name: apply-manifests
      taskRef:
        name: apply-manifests-task
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: apikey
          value: $(params.apikey)
        - name: cluster
          value: $(params.cluster)
        - name: clusterRegion
          value: $(params.clusterRegion)
        - name: manifestPath
          value: $(params.manifestPath)
      workspaces:
        - name: task-pvc
          workspace: pipeline-pvc
